/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
skycons.play();
  // on Android, a nasty hack is needed: {"resizeClear": true}

var set_icon_state = function(date, state) {
  if(state.search("Sunny") >= 0){
    skycons.set(date, Skycons.CLEAR_DAY);
  }else if(state.search("Clear") >= 0){
    skycons.set(date, Skycons.CLEAR_NIGHT);
  }else if(state.search("Rain") >= 0 || state.search("Shower") >= 0 || state.search("Storms") >= 0){
    skycons.set(date, Skycons.RAIN);
  }else if(state.search("Cloudy") >= 0){
    skycons.set(date, Skycons.CLOUDY);
  }else if(state.search("Windy") >= 0){
    skycons.set(date, Skycons.WIND);
  }else if(state.search("Foggy") >= 0){
    skycons.set(date, Skycons.FOG);
  }else if(state.search("Snow") >= 0){
    skycons.set(date, Skycons.SNOW);
  }
};

var get_city = function(city) {
  $.getJSON(
    'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"' + city + '")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', {},
      function(data, state) {
        console.log('data', data);
        $('.temperature').text(toCelsius(data.query.results.channel.item.condition.temp));
        $('.date').text(data.query.results.channel.item.forecast[0].date);
        $('.state').text(': ' + data.query.results.channel.item.condition.text);
        $(".date_now > th:nth-child(1)").text(data.query.results.channel.item.forecast[1].date);
        $(".date_now > th:nth-child(2)").text(data.query.results.channel.item.forecast[2].date);
        $(".date_now > th:nth-child(3)").text(data.query.results.channel.item.forecast[3].date);
        $(".temp_now > td:nth-child(1)").text(toCelsius(data.query.results.channel.item.forecast[1].low) + " - " + toCelsius(data.query.results.channel.item.forecast[1].high) + " ℃");
        $(".temp_now > td:nth-child(2)").text(toCelsius(data.query.results.channel.item.forecast[2].low) + " - " + toCelsius(data.query.results.channel.item.forecast[2].high) + " ℃");
        $(".temp_now > td:nth-child(3)").text(toCelsius(data.query.results.channel.item.forecast[3].low) + " - " + toCelsius(data.query.results.channel.item.forecast[3].high) + " ℃");

        set_icon_state("today", data.query.results.channel.item.condition.text);
        set_icon_state("day1", data.query.results.channel.item.forecast[1].text);
        set_icon_state("day2", data.query.results.channel.item.forecast[2].text);
        set_icon_state("day3", data.query.results.channel.item.forecast[3].text);
      }
  );
};
  // you can add a canvas by it's ID...
  // skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  // skycons.add("day1", Skycons.CLEAR_DAY);
  // skycons.add("day2", Skycons.CLOUDY);
  // skycons.add("day3", Skycons.RAIN);

  // start animation!
  // skycons.play();
  
  // want to change the icon? no problem:
  // skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$(function() {
  get_city('Taipei');
  $('#dropdown li').on('click', function() {
    alert($(this).text());
    $('button').text($(this).text());
    get_city($(this).attr("id"));
  });
});

var toCelsius = function(f) {
  return Math.round((f-32) * 5 / 9);
}